#!/bin/bash
set -e

# ProvenanceAI Metagraph Deployment - Script 6: Deploy to IntegrationNet
# Purpose: Configure and deploy metagraph to Constellation IntegrationNet

echo "=========================================="
echo "Script 6: Deploy to IntegrationNet"
echo "=========================================="
echo ""

LOG_FILE="/root/provenanceai-metagraph/logs/06_deploy_integrationnet.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "Log file: $LOG_FILE"
echo "Started at: $(date)"
echo ""

cd /root/provenanceai-metagraph/euclid-development-environment

# Configure remote deployment
echo "[1/4] Configuring remote deployment..."

# Create Ansible hosts file
mkdir -p infra/ansible/remote
cat > infra/ansible/remote/hosts.ansible.yml <<'EOF'
all:
  children:
    global_l0:
      hosts:
        node1:
          ansible_host: 198.144.183.32
          ansible_user: root
          ansible_connection: local

    metagraph_l0:
      hosts:
        node1:
          ansible_host: 198.144.183.32
          ansible_user: root
          ansible_connection: local

    currency_l1:
      hosts:
        node1:
          ansible_host: 198.144.183.32
          ansible_user: root
          ansible_connection: local

    data_l1:
      hosts:
        node1:
          ansible_host: 198.144.183.32
          ansible_user: root
          ansible_connection: local
EOF

echo "Ansible hosts configured"
echo ""

# Generate P12 key files if they don't exist
echo "[2/4] Generating P12 key files..."
if [ ! -f "source/p12-files/genesis.p12" ]; then
    mkdir -p source/p12-files
    # Note: Hydra should generate these automatically, but we'll create a placeholder note
    echo "P12 files should be generated by Hydra during first start"
else
    echo "P12 files already exist"
fi
echo ""

# Start metagraph locally first (to generate keys and initialize)
echo "[3/4] Starting metagraph (initial setup)..."
echo "This will start the metagraph in local mode first..."

# Start genesis
scripts/hydra start-genesis &
GENESIS_PID=$!

# Wait for initialization
echo "Waiting for nodes to initialize (60 seconds)..."
sleep 60

# Check status
scripts/hydra status || echo "Status check failed, continuing..."

# Stop local instance
echo "Stopping local instance..."
scripts/hydra stop
wait $GENESIS_PID 2>/dev/null || true

echo ""

# Deploy to IntegrationNet
echo "[4/4] Deploying to IntegrationNet..."
echo "Starting metagraph nodes..."

# Start in integrationnet mode
scripts/hydra start-genesis --network integrationnet &

# Wait for startup
echo "Waiting for nodes to start and connect to IntegrationNet (90 seconds)..."
sleep 90

# Check status
echo ""
echo "Checking metagraph status..."
scripts/hydra status

echo ""
echo "=========================================="
echo "✅ Metagraph Deployed to IntegrationNet!"
echo "=========================================="
echo ""
echo "Endpoints (should be accessible):"
echo "- Data L1: http://198.144.183.32:9400"
echo "- Metagraph L0: http://198.144.183.32:9200"
echo ""
echo "Next step: Run ./07_verify_deployment.sh"
echo ""
